/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get price information for the given Scryfall URLs. */
        get: operations["get_prices_prices_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** FinishEntry */
        FinishEntry: {
            /** Url */
            url: string;
            /** Price */
            price: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** PriceEntry */
        PriceEntry: {
            manaPool?: components["schemas"]["VendorEntry"] | null;
            cardKingdom?: components["schemas"]["VendorEntry"] | null;
            cardsphere?: components["schemas"]["VendorEntry"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** VendorEntry */
        VendorEntry: {
            nonfoil?: components["schemas"]["FinishEntry"] | null;
            foil?: components["schemas"]["FinishEntry"] | null;
            etched?: components["schemas"]["FinishEntry"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_prices_prices_get: {
        parameters: {
            query?: {
                /** @description List of Scryfall card URLs to retrieve price information for. */
                url?: string[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: components["schemas"]["PriceEntry"];
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
